version: '3.3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27100:27017'
  api:
    container_name: deploying-docker
    build: './'
    ports:
      - '8080:8080'
    depends_on:
      - mongo